sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - dev
before_script:
- npm install -g @angular/cli
- npm install
script:
- ng lint
- npm run test-chromeheadless
- npm run postinstall
deploy:
  provider: heroku
  api_key:
    secure: HLxKBPmb/DAcMpuLDTbR5UmYC2tnbf0X3q/WG5GSv8vqjPvRK3XE0akzENpMowvHCfJvcYzEqjL2XW4lNKv6MRZo2mGamfKdljyUvtce3A1rkj/8XraV4cEqH80kTOgzWyQwDLpRi6t8O+EeTr6PpS9VCJ8DAKyyZGlntX4Bc4BRmanohKnOfk86fVAEZ95qqVL/MF7amtyF9VqoptPLp6oDlw/FyWlfEukpRjZ0fMnvktjOYOM+yv4yYt8oK8Z7RJs2nQR63timbCNaZLJPnHHJBeMtMTMTcpJotkT0EiQJq00ru78d6gOs2VzvOiWHT6GHviIYu32tB3rVvrRLzePKfMp4Ia3YRdG32hxrIyp+7GbU28ysPf+xVnWuUeuquU4pegwvueB58K7Hgv0trEXlXSfn8rRd+YdwQCiy0Zu2DkfsmxXKxsfW0awxBFTFU3f5rW2Pcsi9PupJYQ1gHnahJ8nq4wO4TO4OCnzrI2W4TBavbOu4wcuOEY/WaAK0XTAjec1UFzBNOgNPdjDgwbxBxVj3IZQ5aFbGsmapIISO5T8zOmYKSnJll6E692WknFuc+YkAfN8N+AJCDGkdJLerYiV+jlCdn0cZgw+lqcOQSlIfnubKNIu9puz/dfOxwowTxNiu3gyuIE+gGmszT22ODP0TrGeJcsRxpeHTpl8=
  app:
    master: my-reading-books
    dev: my-reading-books-dev
